### ISSUE TITLE
Create authenticated user dashboard

### ISSUE THREAD

**Issue by nhepner1** [Unallocated/UASDrupal#110]
Create authenticated user dashboard that contains the following sections:
- Announcments
- Latest Groups Content
- My Groups
- Upcoming Events
- My Projects
- Latest Resources

This ticket relies on:
- [x] Create new theme region #111 
- [x] Create a "My Projects" view #112
- [x] Create a "My Groups" view #113
- [x] Update announcements view with /member-home view #115
- [x] Create a frontpage context for authenticated users 
- [x] Install and configure front module to set new home page. #114
- [x] Install and configure the login destination module. #114
- [x] Create the "Latest Group Content" view #116
- [x] Create Delta for front page authenticated #127

**Comment by nhepner1** [comment]
This issue has been resolved and merged into 7.x-1.x-dev
